// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender               bool     `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	HasAnyPets           bool     `protobuf:"varint,6,opt,name=hasAnyPets,proto3" json:"hasAnyPets,omitempty"`
	Employed             bool     `protobuf:"varint,7,opt,name=employed,proto3" json:"employed,omitempty"`
	Age                  int32    `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Profile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Profile) GetGender() bool {
	if m != nil {
		return m.Gender
	}
	return false
}

func (m *Profile) GetHasAnyPets() bool {
	if m != nil {
		return m.HasAnyPets
	}
	return false
}

func (m *Profile) GetEmployed() bool {
	if m != nil {
		return m.Employed
	}
	return false
}

func (m *Profile) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type UpdateRequest struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type CreateRequest struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type DeleteRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type GetByLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByLoginRequest) Reset()         { *m = GetByLoginRequest{} }
func (m *GetByLoginRequest) String() string { return proto.CompactTextString(m) }
func (*GetByLoginRequest) ProtoMessage()    {}
func (*GetByLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *GetByLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByLoginRequest.Unmarshal(m, b)
}
func (m *GetByLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByLoginRequest.Marshal(b, m, deterministic)
}
func (m *GetByLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByLoginRequest.Merge(m, src)
}
func (m *GetByLoginRequest) XXX_Size() int {
	return xxx_messageInfo_GetByLoginRequest.Size(m)
}
func (m *GetByLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByLoginRequest proto.InternalMessageInfo

func (m *GetByLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type GetByLoginResponse struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByLoginResponse) Reset()         { *m = GetByLoginResponse{} }
func (m *GetByLoginResponse) String() string { return proto.CompactTextString(m) }
func (*GetByLoginResponse) ProtoMessage()    {}
func (*GetByLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *GetByLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByLoginResponse.Unmarshal(m, b)
}
func (m *GetByLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByLoginResponse.Marshal(b, m, deterministic)
}
func (m *GetByLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByLoginResponse.Merge(m, src)
}
func (m *GetByLoginResponse) XXX_Size() int {
	return xxx_messageInfo_GetByLoginResponse.Size(m)
}
func (m *GetByLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByLoginResponse proto.InternalMessageInfo

func (m *GetByLoginResponse) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type SuccessResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingRequest) Reset()         { *m = ListingRequest{} }
func (m *ListingRequest) String() string { return proto.CompactTextString(m) }
func (*ListingRequest) ProtoMessage()    {}
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{7}
}

func (m *ListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingRequest.Unmarshal(m, b)
}
func (m *ListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingRequest.Marshal(b, m, deterministic)
}
func (m *ListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingRequest.Merge(m, src)
}
func (m *ListingRequest) XXX_Size() int {
	return xxx_messageInfo_ListingRequest.Size(m)
}
func (m *ListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingRequest proto.InternalMessageInfo

type ListingResponse struct {
	Profiles             []*Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListingResponse) Reset()         { *m = ListingResponse{} }
func (m *ListingResponse) String() string { return proto.CompactTextString(m) }
func (*ListingResponse) ProtoMessage()    {}
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{8}
}

func (m *ListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingResponse.Unmarshal(m, b)
}
func (m *ListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingResponse.Marshal(b, m, deterministic)
}
func (m *ListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingResponse.Merge(m, src)
}
func (m *ListingResponse) XXX_Size() int {
	return xxx_messageInfo_ListingResponse.Size(m)
}
func (m *ListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingResponse proto.InternalMessageInfo

func (m *ListingResponse) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "protocol.Profile")
	proto.RegisterType((*UpdateRequest)(nil), "protocol.UpdateRequest")
	proto.RegisterType((*CreateRequest)(nil), "protocol.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "protocol.DeleteRequest")
	proto.RegisterType((*GetByLoginRequest)(nil), "protocol.GetByLoginRequest")
	proto.RegisterType((*GetByLoginResponse)(nil), "protocol.GetByLoginResponse")
	proto.RegisterType((*SuccessResponse)(nil), "protocol.SuccessResponse")
	proto.RegisterType((*ListingRequest)(nil), "protocol.ListingRequest")
	proto.RegisterType((*ListingResponse)(nil), "protocol.ListingResponse")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4b, 0x4b, 0xeb, 0x40,
	0x14, 0x26, 0x7d, 0x24, 0xb9, 0xe7, 0xd2, 0xd7, 0x70, 0xb9, 0x8e, 0x55, 0xa4, 0x04, 0x84, 0x4a,
	0xb1, 0x8b, 0xba, 0x2d, 0x62, 0x55, 0xe8, 0xa6, 0x8b, 0x92, 0xe2, 0x0f, 0x88, 0xc9, 0x31, 0x06,
	0xd2, 0x4c, 0xcc, 0xa4, 0x4a, 0x7f, 0xa5, 0x0b, 0xff, 0x90, 0x64, 0x32, 0x79, 0xd5, 0x52, 0xd1,
	0x55, 0xf3, 0xbd, 0xa6, 0xe7, 0x9c, 0x0f, 0x5a, 0x61, 0xc4, 0x9e, 0x3c, 0x1f, 0xc7, 0x61, 0xc4,
	0x62, 0x46, 0x74, 0xf1, 0x63, 0x33, 0xdf, 0x78, 0x57, 0x40, 0x5b, 0xa6, 0x1a, 0xf9, 0x07, 0x4d,
	0x9f, 0xb9, 0x5e, 0x40, 0x95, 0x81, 0x32, 0xfc, 0x63, 0xa6, 0x80, 0xf4, 0x41, 0x0f, 0x2d, 0xce,
	0xdf, 0x58, 0xe4, 0xd0, 0x9a, 0x10, 0x72, 0x4c, 0x08, 0x34, 0x02, 0x6b, 0x8d, 0xb4, 0x2e, 0x78,
	0xf1, 0x4d, 0x28, 0x68, 0x7c, 0x13, 0x09, 0xba, 0x21, 0xe8, 0x0c, 0x92, 0xff, 0xa0, 0xba, 0x18,
	0x38, 0x18, 0xd1, 0xe6, 0x40, 0x19, 0xea, 0xa6, 0x44, 0xe4, 0x0c, 0xe0, 0xd9, 0xe2, 0xb3, 0x60,
	0xbb, 0xc4, 0x98, 0x53, 0x55, 0x68, 0x25, 0x26, 0x99, 0x00, 0xd7, 0xa1, 0xcf, 0xb6, 0xe8, 0x50,
	0x4d, 0xa8, 0x39, 0x26, 0x5d, 0xa8, 0x5b, 0x2e, 0x52, 0x7d, 0xa0, 0x0c, 0x9b, 0x66, 0xf2, 0x69,
	0x4c, 0xa1, 0xf5, 0x10, 0x3a, 0x56, 0x8c, 0x26, 0xbe, 0x6c, 0x90, 0xc7, 0x64, 0x04, 0x9a, 0xdc,
	0x5e, 0x2c, 0xf6, 0x77, 0xd2, 0x1b, 0x67, 0xeb, 0x8f, 0xe5, 0xea, 0x66, 0xe6, 0x48, 0xd2, 0x77,
	0x11, 0xfe, 0x36, 0x7d, 0x0e, 0xad, 0x7b, 0xf4, 0xb1, 0x48, 0xef, 0x3d, 0xa9, 0x71, 0x01, 0xbd,
	0x39, 0xc6, 0xb7, 0xdb, 0x45, 0x82, 0x0e, 0x5b, 0x67, 0x40, 0xca, 0x56, 0x1e, 0xb2, 0x80, 0xe3,
	0xcf, 0x86, 0x1a, 0x41, 0x67, 0xb5, 0xb1, 0x6d, 0xe4, 0x3c, 0xcf, 0x8b, 0x8e, 0x04, 0x25, 0xf2,
	0xba, 0x99, 0x41, 0xa3, 0x0b, 0xed, 0x85, 0xc7, 0x63, 0x2f, 0x70, 0xe5, 0x5c, 0xc6, 0x0d, 0x74,
	0x72, 0x46, 0xc6, 0x2f, 0x41, 0x97, 0x8f, 0x27, 0xf9, 0xfa, 0xfe, 0xff, 0xcf, 0x2d, 0x93, 0x8f,
	0x1a, 0xb4, 0x25, 0xbb, 0xc2, 0xe8, 0xd5, 0xb3, 0x91, 0x4c, 0x41, 0x4d, 0xcf, 0x4c, 0x8e, 0x8a,
	0x64, 0xe5, 0xf0, 0xfd, 0xe3, 0x42, 0xd8, 0x1d, 0x7f, 0x0a, 0x6a, 0x5a, 0x71, 0x39, 0x5d, 0x29,
	0xfd, 0x9b, 0x74, 0x5a, 0x52, 0x39, 0x5d, 0xa9, 0xed, 0x50, 0x7a, 0x0e, 0x50, 0x14, 0x42, 0x4e,
	0x0a, 0xe3, 0x97, 0x46, 0xfb, 0xa7, 0xfb, 0x45, 0xf9, 0xd0, 0x35, 0x68, 0xf2, 0xae, 0x84, 0x16,
	0xc6, 0xea, 0xf1, 0xcb, 0x83, 0xec, 0x94, 0xf0, 0xa8, 0x0a, 0xe5, 0xea, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x23, 0x1c, 0xb5, 0x6a, 0xdb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	GetByLogin(ctx context.Context, in *GetByLoginRequest, opts ...grpc.CallOption) (*GetByLoginResponse, error)
	Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/protocol.ProfileService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/protocol.ProfileService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/protocol.ProfileService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetByLogin(ctx context.Context, in *GetByLoginRequest, opts ...grpc.CallOption) (*GetByLoginResponse, error) {
	out := new(GetByLoginResponse)
	err := c.cc.Invoke(ctx, "/protocol.ProfileService/GetByLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, "/protocol.ProfileService/Listing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	Create(context.Context, *CreateRequest) (*SuccessResponse, error)
	Update(context.Context, *UpdateRequest) (*SuccessResponse, error)
	Delete(context.Context, *DeleteRequest) (*SuccessResponse, error)
	GetByLogin(context.Context, *GetByLoginRequest) (*GetByLoginResponse, error)
	Listing(context.Context, *ListingRequest) (*ListingResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Create(ctx context.Context, req *CreateRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProfileServiceServer) Update(ctx context.Context, req *UpdateRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProfileServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedProfileServiceServer) GetByLogin(ctx context.Context, req *GetByLoginRequest) (*GetByLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByLogin not implemented")
}
func (*UnimplementedProfileServiceServer) Listing(ctx context.Context, req *ListingRequest) (*ListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listing not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ProfileService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ProfileService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ProfileService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetByLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetByLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ProfileService/GetByLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetByLogin(ctx, req.(*GetByLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ProfileService/Listing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Listing(ctx, req.(*ListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProfileService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProfileService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProfileService_Delete_Handler,
		},
		{
			MethodName: "GetByLogin",
			Handler:    _ProfileService_GetByLogin_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _ProfileService_Listing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
